### PR TITLE
#10 - Serve JS dependencies.

### PR DESCRIPTION
**Pull request by FrazerSeymour**
This is a super lazy approach, and wouldn't be ideal if I didn't know I will be using `vulcanize` for #12 which will strip out the links and just dump the code inline.

Also a shame that we don't have `socket.io.min.js`, but an uglifier down the line should deal with that.

### CODE REVIEW

**Comment by FrazerSeymour** [comment]
@nathanielhudson - do we want to :+1:/:shipit:/otherwise code review PRs first? Or #yolo merge?

**Comment by nathanielhudson** [comment]
No reason not to check over. Looks good to me! 🚢

**Comment by FrazerSeymour** [comment]
Probably leave closing it to the author though.

**Comment by nathanielhudson** [comment]
Sure thing.

**Pull request merged**
